### ISSUE TITLE
Funny Stories

### ISSUE THREAD

**Issue by dykesb** [STA518-Spring20/activity0101-forking-issues#1]
Tell a funny story of a time your teacher or professor did not understand how to use technology.

I'll start things off! In grad school when I was student teaching, I *forgot* that the projector screen was down and started circling items from the slide I was projecting with the dry erase marker I was holding. Dry eraser markers erase very easily from a whiteboard, but not so much so from a projector screen 🤦 

I **always** double-check the screen's status now...

**Comment by hayley-chelotti** [comment]
Don't feel bad, I have witnessed the same thing happen *at least five times* during my educational career. However, when I was taking CIS 150, I witnessed a phenomenon that was truly unique. The professor could not get his computer to turn on and struggled to do so for about 15 minutes before contacting IT support. The technician arrived and resolved his problem in about 15 seconds, **by plugging the computer into the wall**.

**Comment by ralythompson24** [comment]
One year when I was in high school our school bought a smart board for every class room. Not only were there several incidents of teachers accidentally using dry-erase markers on them (which doesn't wipe off very easy), the teachers all *loathed* them (or more likely just didn't know how to use them) and so they just ended up taking valuable whiteboard space :roll_eyes: **#fail**

**Comment by monsadan** [comment]
On the past semester, one professor was sharing his screen while make a presentation, in some slides there was some questions for the students. When he share the screen all the class was seeing the presentation like this:
![image](https://user-images.githubusercontent.com/54322798/81017155-d1a3c700-8e2f-11ea-9830-c2a8d210f004.png)
He had **ALL THE ANSWERS** in the notes space, so we can read it all. Those was some very easy  questions to answer  :hand_over_mouth:

**Comment by jasonrsmith99** [comment]
I work for IT on campus so I have quite a few stories. One of my favorites is a professor who accidentally flipped her screen **upside down** (control+alt+arrow keys) when they were using Excel. My guess is that they were trying to skip to the end of a column (control+**shift**+arrow keys).

**Comment by fracassc** [comment]
I also worked for IT on campus in undergrad. A Professor once called asking...
### How to delete an email
I explained that there really are quite a few ways; hit the delete key on your keyboard, hit the trash icon, and I mentioned that Outlook will have a red 'X' next to the email as well. They said they saw the red 'X', but upon hitting that 'X' they stated that everything disappeared. _They had hit the close button on all of Outlook._

**Comment by dirksem** [comment]
Just last semester I had a professor schedule an online Blackboard exam that never showed up at the scheduled time.  He didn't notice until **after the exam window** so we had to take it the next day instead.  I think a lot of students, including myself, were in a *PANIC*!!

**Comment by joblara8** [comment]
I can't think of any examples of professors not knowing how to use technology at the moment, but at my work there are a handful of people who I think have pretty limited computer skills, e.g. not knowing how to log in. They provide indispensable value in other areas but that's perhaps why they have never learned the more basic computer skills.

**Comment by joblara8** [comment]
I can't think of any examples of professors not knowing how to use technology at the moment, but at my work there are a handful of people who I think have pretty limited computer skills, e.g. not knowing how to log in. They provide indispensable value in other areas but that's perhaps why they have never learned **the more basic computer skills.**

**Comment by hendrmat** [comment]
Last semester, I had a professor who admittedly was not well-versed in technology.  They could not remember the password to their YouTube account but did not want to take the time to reset the password (as it was class time).  Since I have been in a similar situation with _innocent_ videos being marked as not safe and needing an account to view, I taught them the trick to view the video by updating the URL with **nsfw**youtube.com/blahblah.  It brought up the video (this was a biology class) and all was well!

**Comment by Hab25blu** [comment]
I don't have any hilarious or great stories with technology with professors. There is one about a specific professor that has poofy hair more than Einstein or anyone else worst bedhead day.  One day the professor was alternating between projector, writing on the white board and walking around class to interact with students for the lesson. At one point in the lesson he was about to write on the white board and **couldn't find the marker**.  After a while he requested a few people to help him search and we couldn't find that specific marker and he was refusing to use the other colored markers and was persistent at finding the missing marker. At this point he said _"I just don't understand where it could have gone!"_ and he scratches the side of his head and then he gave the class huge embarrassed grin and started chuckling. He realized he had put the marker behind his ear. When he clarified to the class what had happen everyone including him burst into uncontrollable laughter for about 10 minutes. **That was a great class!**

**Comment by bakjinn** [comment]
I went to a middle school that got a grant for magic white boards, they were electronic and had a bunch of features to *help* with the learning experience; it was a huge learning curve for all the teachers to get adjusted to using this new technology. They were all forced to use the new magic boards so it was funny seeing the teachers grumble about figuring it out during class.

**Comment by schmimol** [comment]
I can't think of any off the top of my head, but I have definitely had professors do funny things with the projector/ projector screen.

**Comment by omarRmalik** [comment]
I was teaching at Ohio Northern and they switched to smartboards one summer. I walked into class with my markers and realized I had not paid attention to all the emails regarding smartboards. However, the students had seen them used and they demonstrated to me how to use a smartboard. I learnt from them.

**Comment by Rand3rino** [comment]
Nothing big comes to mind, the _freeze_ button on the projector console does give some people the slip though. Whether it should be on and it isn't or vice versa.

**Comment by Nelskika** [comment]
I had a professor who needed to use the projector to show a PowerPoint and had forgot their laptop at home, They tried to use the computer in the classroom but couldn't get  to work so they called IT and when they got there it was revealed _the  computer just wasn't turned on._

**Comment by KhileahWilliams** [comment]
My professor last semester did not know how to upload an exam online when we switched to online learning. So the exam was just postponed until he could figure it out. He said it was the worst experience _lol_ so we ended up finishing the semester with video exams. **#AmazingProfessorAndClass.**

**Comment by shroom552** [comment]
My story was going to be about how a professor used a marker on a projector screen.... Since that one was taken I'll tell you a story about how I caught bad equations in a professors excel sheet. It was a Creative storytelling class and no one had much of an issue receiving high scores on the assignments yet the highest grade was a 85%. When I realized my grade was about 10% lower than expected going into the final exam I crunched the numbers over and over and turns out all quiz scores for the semester were not being counted towards our final grade but the possible quiz points were... Someone how received 100% on all quizzes was being deducted __15%__ of their final grade.

**Comment by sharnjitvirk** [comment]
I had a professor who was meant to post our final exam online for a ~3 hour window. He had explained that he wouldn't be checking his email to answer questions since it was an open note exam. **He didn't post the exam.** I'm sure many students emailed him but since he wasn't checking his email he didn't find out until the next day that nobody took the final exam. I think it was funny because he just flat out said he wasn't going to answer emails and so we had no way to reach him.

**Comment by NickDuley** [comment]
My sophomore year of college, I had a professor that could not get a video to play on the projector. Needless to say, after waiting for GV IT to arrive to solve the problem, it was found that the only issue was that my professor did not press the change input button...**yep...**

**Comment by daymonjohnson** [comment]
I honestly can't remember a single time when this has happened. I am pretty sure every semester I have ever had something has gone wrong at some point. My dad is a college professor though and the other day I had to help him figure out how to get a file on his phone on to the computer. **I made fun of him for not knowing any ways to do that.**

**Comment by jaydfox** [comment]
I was teaching STA 215 in the computer lab and the computer would not turn on. I checked the power cords to make sure they were plugged in. I re-tried pressing the power button. Finally I called IT help desk to fix the problem. Right when they arrived I realized the instructor workstation had a master power power that was off. **Now I know**

**Comment by millerp217** [comment]
There have been a few times when Professors have the students present from their own files/device.  **Inevitably** this devolves into a bartering session to see if anyone has the appropriate and/or obscure input adapter in their bag.

**Comment by GriffinGoing** [comment]
I once had a c# teacher (at another college) who's lecture videos rapidly alternated between being ***WAY*** too loud, to way too *sooooooft*. Additionally, they were all rotated either **90** or **180** degrees. Truly terrifying.

**Comment by daudling** [comment]
I once had to show a teacher where the input jack for her headphones were on her laptop. There was a **picture of headphones** clearly visible.

**Comment by dadrian14** [comment]
Looking at this too late.  Nice thread!
